// Package turn embeds a pion/turn v5 STUN+TURN server in the same Go process
// as the SFU. Authentication uses the standard TURN REST API HMAC scheme so
// short-term credentials can be generated by the HTTP backend and validated
// here from a single shared secret.
package turn

import (
	"crypto/hmac"
	"crypto/sha1"
	"encoding/base64"
	"fmt"
	"log"
	"net"
	"strconv"
	"time"

	pionlogging "github.com/pion/logging"
	pion "github.com/pion/turn/v5"
)

// Config controls the embedded TURN server.
type Config struct {
	// Realm advertised in TURN responses; usually the public hostname.
	Realm string
	// SharedSecret backs the TURN REST HMAC scheme. Must match the secret
	// used by the credentials generator.
	SharedSecret string
	// PublicIP is the externally-reachable address advertised in relay
	// candidates. For docker hosts this is the host's public IP.
	PublicIP string
	// ListenAddr is the bind address for the STUN/TURN UDP listener.
	ListenAddr string
	// MinRelayPort/MaxRelayPort define the UDP port range allocated to relay
	// peers. Must be exposed by the container.
	MinRelayPort uint16
	MaxRelayPort uint16
}

// Server wraps a pion/turn server.
type Server struct {
	srv *pion.Server
}

// Start brings up the TURN listener.
func Start(cfg Config) (*Server, error) {
	if cfg.SharedSecret == "" {
		return nil, fmt.Errorf("turn: shared secret required")
	}
	if cfg.PublicIP == "" {
		return nil, fmt.Errorf("turn: public IP required")
	}
	if cfg.MinRelayPort == 0 || cfg.MaxRelayPort < cfg.MinRelayPort {
		return nil, fmt.Errorf("turn: relay port range invalid (%d-%d)", cfg.MinRelayPort, cfg.MaxRelayPort)
	}

	listener, err := net.ListenPacket("udp4", cfg.ListenAddr)
	if err != nil {
		return nil, fmt.Errorf("turn: listen %s: %w", cfg.ListenAddr, err)
	}

	logger := pionlogging.NewDefaultLoggerFactory().NewLogger("turn")

	// pion defaults AllocationLifetime/ChannelBindTimeout/PermissionTimeout to 10 minutes,
	// which silently kills any call relaying through TURN at the 10-minute mark. Bump to
	// 8 hours so a long call doesn't get torn down mid-conversation.
	const turnAllocationLifetime = 8 * time.Hour

	srv, err := pion.NewServer(pion.ServerConfig{
		Realm:              cfg.Realm,
		AuthHandler:        pion.LongTermTURNRESTAuthHandler(cfg.SharedSecret, logger),
		AllocationLifetime: turnAllocationLifetime,
		ChannelBindTimeout: turnAllocationLifetime,
		PermissionTimeout:  turnAllocationLifetime,
		PacketConnConfigs: []pion.PacketConnConfig{
			{
				PacketConn: listener,
				RelayAddressGenerator: &pion.RelayAddressGeneratorPortRange{
					RelayAddress: net.ParseIP(cfg.PublicIP),
					Address:      "0.0.0.0",
					MinPort:      cfg.MinRelayPort,
					MaxPort:      cfg.MaxRelayPort,
				},
			},
		},
	})
	if err != nil {
		_ = listener.Close()
		return nil, fmt.Errorf("turn: server: %w", err)
	}

	log.Printf("turn: listening on %s, relay %s:%d-%d, realm=%s",
		cfg.ListenAddr, cfg.PublicIP, cfg.MinRelayPort, cfg.MaxRelayPort, cfg.Realm)

	return &Server{srv: srv}, nil
}

// Close stops the TURN server.
func (s *Server) Close() error {
	if s == nil {
		return nil
	}
	return s.srv.Close()
}

// GenerateCredentials returns a TURN REST API short-term username/credential
// pair valid for ttl. The username encodes expiry as required by the spec:
// `<unix_expiry>:<id>`. The credential is base64(HMAC-SHA1(secret, username)).
//
// Spec: https://datatracker.ietf.org/doc/html/draft-uberti-rtcweb-turn-rest-00
func GenerateCredentials(secret, id string, ttl time.Duration) (username, credential string) {
	if id == "" {
		id = "anon"
	}
	expiry := time.Now().Add(ttl).Unix()
	username = strconv.FormatInt(expiry, 10) + ":" + id
	mac := hmac.New(sha1.New, []byte(secret))
	mac.Write([]byte(username))
	credential = base64.StdEncoding.EncodeToString(mac.Sum(nil))
	return
}
