package sfu

import (
	"github.com/pion/interceptor"
	"github.com/pion/rtp"
	"github.com/pion/webrtc/v4"
)

// rtxPacerFactory wraps the cc interceptor so each local stream's RTX SSRC is
// registered with the gcc pacer too. The pacer routes by header SSRC and
// rejects unknown ones, so without this every retransmission fails with
// gcc.ErrUnknownStream.
type rtxPacerFactory struct{ interceptor.Factory }

func (f rtxPacerFactory) NewInterceptor(id string) (interceptor.Interceptor, error) {
	i, err := f.Factory.NewInterceptor(id)
	if err != nil {
		return nil, err
	}
	return rtxPacer{i}, nil
}

type rtxPacer struct{ interceptor.Interceptor }

func (p rtxPacer) BindLocalStream(info *interceptor.StreamInfo, writer interceptor.RTPWriter) interceptor.RTPWriter {
	if info.SSRCRetransmission != 0 {
		rtx := *info
		rtx.SSRC = info.SSRCRetransmission
		p.Interceptor.BindLocalStream(&rtx, writer)
	}
	return p.Interceptor.BindLocalStream(info, writer)
}

// forwardable reports whether a packet read from a publisher's video track
// carries new media. The SFU never NACKs publishers and renumbers by arrival,
// so both kinds of drops would otherwise reach subscribers as fresh packets:
//   - padding-only BWE probes (empty payload once padding is stripped);
//   - anything pion unwrapped from the publisher's RTX stream, if negotiated:
//     redundant copies Chrome sends as probe payload, i.e. media already
//     forwarded.
//
// TWCC feedback for both is generated by the interceptors before Read returns.
func forwardable(pkt *rtp.Packet, attrs interceptor.Attributes) bool {
	return len(pkt.Payload) > 0 && attrs.Get(webrtc.AttributeRtxSsrc) == nil
}
